### ISSUE TITLE
saver.restore：report error

### ISSUE THREAD

**Issue by GuanLin-Wu** [andrew-j-levy/Pre-Trained-Skills#1]
When executing the command 'python3 run_random_agent.py --show --subgoals' , it will report error that 'tensorflow.python.framework.errors_impl.NotFoundError: /Users/andrewlevy/Documents/HAC/skills/lay_3_min_ep30_gear_15/models; No such file or directory '. (when self.saver.restore(self.sess, tf.train.latest_checkpoint(self.model_dir)))

**Comment by GuanLin-Wu** [comment]
I have found how to solve this problem. Please remind users to update the new local 'model path' in /models/checkpoint

**Comment by andrew-j-levy** [comment]
Thanks for the heads up!  I added a note in the README that the file paths in the checkpoint file need to be updated.
